import type { Materia } from '@/types/database'

export const MATERIAS: { value: Materia; label: string }[] = [
  { value: 'civil', label: 'Civil' },
  { value: 'mercantil', label: 'Mercantil' },
  { value: 'laboral', label: 'Laboral' },
  { value: 'familia', label: 'Familia, niñez y adolescencia' },
  { value: 'penal', label: 'Penal' },
  { value: 'transito', label: 'Tránsito' },
  { value: 'inquilinato', label: 'Inquilinato' },
  { value: 'contencioso_administrativo', label: 'Contencioso administrativo' },
  { value: 'contencioso_tributario', label: 'Contencioso tributario' },
  { value: 'constitucional', label: 'Constitucional' },
  { value: 'asesoria', label: 'Asesoría / Gestión' },
  { value: 'otro', label: 'Otro' },
]

export const MATERIA_LABEL: Record<Materia, string> = Object.fromEntries(
  MATERIAS.map((m) => [m.value, m.label]),
) as Record<Materia, string>

type Opcion = { value: string; label: string }

export const TIPOS_ACCION: Record<Materia, Opcion[]> = {
  civil: [
    { value: 'cobro_ordinario', label: 'Cobro de dinero — ordinario' },
    { value: 'cobro_ejecutivo', label: 'Cobro de dinero — ejecutivo' },
    { value: 'cobro_monitorio', label: 'Cobro de dinero — monitorio' },
    { value: 'danos_perjuicios', label: 'Daños y perjuicios' },
    { value: 'nulidad_contrato', label: 'Nulidad de contrato' },
    { value: 'resolucion_contrato', label: 'Resolución de contrato' },
    { value: 'reivindicacion', label: 'Reivindicación de bien inmueble' },
    { value: 'prescripcion_adquisitiva', label: 'Prescripción adquisitiva de dominio' },
    { value: 'servidumbre', label: 'Servidumbre' },
    { value: 'colusion', label: 'Colusión' },
    { value: 'rendicion_cuentas', label: 'Rendición de cuentas' },
    { value: 'posesion_efectiva', label: 'Posesión efectiva (herencia)' },
    { value: 'apertura_testamento', label: 'Apertura y protocolización de testamento' },
    { value: 'inventario_solemne', label: 'Inventario solemne' },
    { value: 'declaratoria_interdiccion', label: 'Declaratoria de interdicción' },
    { value: 'jurisdiccion_voluntaria', label: 'Jurisdicción voluntaria' },
    { value: 'otro_civil', label: 'Otro civil' },
  ],
  mercantil: [
    { value: 'cobro_cheque', label: 'Cobro ejecutivo — cheque' },
    { value: 'cobro_pagare', label: 'Cobro ejecutivo — pagaré' },
    { value: 'cobro_letra_cambio', label: 'Cobro ejecutivo — letra de cambio' },
    { value: 'cobro_monitorio_mercantil', label: 'Cobro monitorio' },
    { value: 'impugnacion_acto_societario', label: 'Impugnación de acto societario' },
    { value: 'nulidad_contrato_mercantil', label: 'Nulidad de contrato mercantil' },
    { value: 'quiebra', label: 'Quiebra / insolvencia' },
    { value: 'concurso_acreedores', label: 'Concurso de acreedores' },
    { value: 'danos_mercantiles', label: 'Daños y perjuicios mercantiles' },
    { value: 'reconocimiento_firma', label: 'Reconocimiento de firma en título valor' },
    { value: 'otro_mercantil', label: 'Otro mercantil' },
  ],
  laboral: [
    { value: 'despido_intempestivo', label: 'Despido intempestivo' },
    { value: 'visto_bueno_empleador', label: 'Visto bueno — empleador' },
    { value: 'visto_bueno_trabajador', label: 'Visto bueno — trabajador' },
    { value: 'cobro_haberes', label: 'Cobro de haberes y beneficios sociales' },
    { value: 'reinstalacion', label: 'Reinstalación en el cargo' },
    { value: 'acoso_laboral', label: 'Acoso laboral' },
    { value: 'accidente_trabajo', label: 'Accidente de trabajo — indemnización' },
    { value: 'enfermedad_profesional', label: 'Enfermedad profesional — indemnización' },
    { value: 'homologacion_finiquito', label: 'Homologación de acta de finiquito' },
    { value: 'otro_laboral', label: 'Otro laboral' },
  ],
  familia: [
    { value: 'divorcio_contencioso', label: 'Divorcio contencioso' },
    { value: 'divorcio_mutuo_consentimiento', label: 'Divorcio por mutuo consentimiento' },
    { value: 'pension_fijacion', label: 'Pensión alimenticia — fijación' },
    { value: 'pension_aumento', label: 'Pensión alimenticia — aumento' },
    { value: 'pension_rebaja', label: 'Pensión alimenticia — rebaja' },
    { value: 'pension_cobro', label: 'Pensión alimenticia — cobro por incumplimiento' },
    { value: 'tenencia_hijos', label: 'Tenencia de hijos' },
    { value: 'regimen_visitas', label: 'Régimen de visitas' },
    { value: 'patria_potestad_disputa', label: 'Patria potestad — disputa' },
    { value: 'patria_potestad_suspension', label: 'Patria potestad — suspensión' },
    { value: 'reconocimiento_paternidad', label: 'Reconocimiento de paternidad / maternidad' },
    { value: 'impugnacion_paternidad', label: 'Impugnación de paternidad' },
    { value: 'union_hecho_reconocimiento', label: 'Unión de hecho — reconocimiento' },
    { value: 'union_hecho_disolucion', label: 'Unión de hecho — disolución' },
    { value: 'adopcion', label: 'Adopción' },
    { value: 'emancipacion', label: 'Emancipación' },
    { value: 'autorizacion_salida', label: 'Autorización salida del país de menor' },
    { value: 'otro_familia', label: 'Otro familia' },
  ],
  penal: [
    { value: 'homicidio', label: 'Homicidio / Asesinato' },
    { value: 'femicidio', label: 'Femicidio / Sicariato' },
    { value: 'lesiones', label: 'Lesiones' },
    { value: 'violencia_fisica', label: 'Violencia física (intrafamiliar)' },
    { value: 'violencia_psicologica', label: 'Violencia psicológica (intrafamiliar)' },
    { value: 'violencia_sexual', label: 'Violencia sexual' },
    { value: 'secuestro', label: 'Secuestro' },
    { value: 'robo_hurto', label: 'Robo / Hurto' },
    { value: 'estafa', label: 'Estafa' },
    { value: 'abuso_confianza', label: 'Abuso de confianza' },
    { value: 'extorsion', label: 'Extorsión' },
    { value: 'usurpacion', label: 'Usurpación' },
    { value: 'peculado', label: 'Peculado' },
    { value: 'cohecho', label: 'Cohecho / Concusión' },
    { value: 'enriquecimiento_ilicito', label: 'Enriquecimiento ilícito' },
    { value: 'trafico_influencias', label: 'Tráfico de influencias' },
    { value: 'delito_informatico', label: 'Delito informático' },
    { value: 'trafico_sustancias', label: 'Tráfico de sustancias' },
    { value: 'otro_penal', label: 'Otro penal' },
  ],
  transito: [
    { value: 'accidente_danos', label: 'Accidente con daños materiales' },
    { value: 'accidente_lesiones', label: 'Accidente con lesiones' },
    { value: 'accidente_muerte', label: 'Accidente con muerte' },
    { value: 'contravencion_impugnacion', label: 'Contravención de tránsito — impugnación' },
    { value: 'otro_transito', label: 'Otro tránsito' },
  ],
  inquilinato: [
    { value: 'desahucio_falta_pago', label: 'Desahucio — falta de pago' },
    { value: 'desahucio_vencimiento', label: 'Desahucio — vencimiento de contrato' },
    { value: 'desahucio_necesidad', label: 'Desahucio — necesidad del propietario' },
    { value: 'cobro_canones', label: 'Cobro de cánones vencidos' },
    { value: 'cobro_danos_inmueble', label: 'Cobro de daños al inmueble' },
    { value: 'otro_inquilinato', label: 'Otro inquilinato' },
  ],
  contencioso_administrativo: [
    { value: 'impugnacion_acto_admin', label: 'Impugnación de acto administrativo' },
    { value: 'silencio_administrativo', label: 'Silencio administrativo' },
    { value: 'contrato_publico_incumplimiento', label: 'Contrato público — incumplimiento' },
    { value: 'responsabilidad_estado', label: 'Responsabilidad del Estado' },
    { value: 'impugnacion_sancion_disciplinaria', label: 'Impugnación de sanción disciplinaria' },
    { value: 'impugnacion_utilidad_publica', label: 'Impugnación de declaratoria de utilidad pública' },
    { value: 'otro_contencioso_admin', label: 'Otro contencioso administrativo' },
  ],
  contencioso_tributario: [
    { value: 'impugnacion_determinacion_sri', label: 'Impugnación de acto de determinación SRI' },
    { value: 'impugnacion_resolucion_sri', label: 'Impugnación de resolución SRI' },
    { value: 'impugnacion_multa_tributaria', label: 'Impugnación de multa tributaria' },
    { value: 'impugnacion_coactiva_sri', label: 'Impugnación coactiva SRI' },
    { value: 'impugnacion_coactiva_iess', label: 'Impugnación coactiva IESS' },
    { value: 'impugnacion_coactiva_municipio', label: 'Impugnación coactiva municipio' },
    { value: 'otro_contencioso_tributario', label: 'Otro contencioso tributario' },
  ],
  constitucional: [
    { value: 'accion_proteccion', label: 'Acción de protección' },
    { value: 'habeas_corpus', label: 'Habeas corpus' },
    { value: 'habeas_data', label: 'Habeas data' },
    { value: 'acceso_informacion_publica', label: 'Acción de acceso a información pública' },
    { value: 'accion_extraordinaria_proteccion', label: 'Acción extraordinaria de protección' },
    { value: 'medida_cautelar_constitucional', label: 'Medida cautelar constitucional' },
    { value: 'otro_constitucional', label: 'Otro constitucional' },
  ],
  asesoria: [
    { value: 'elaboracion_contrato', label: 'Elaboración de contrato' },
    { value: 'elaboracion_testamento', label: 'Elaboración de testamento' },
    { value: 'constitucion_compania', label: 'Constitución de compañía' },
    { value: 'due_diligence', label: 'Due diligence' },
    { value: 'asesoria_puntual', label: 'Asesoría legal puntual' },
    { value: 'tramite_administrativo', label: 'Trámite administrativo' },
    { value: 'otro_asesoria', label: 'Otro' },
  ],
  otro: [{ value: 'otro', label: 'Otro' }],
}

// Tipos de acción que por su naturaleza nunca son contenciosos.
export const TIPOS_NO_CONTENCIOSOS = new Set([
  'divorcio_mutuo_consentimiento',
  'posesion_efectiva',
  'apertura_testamento',
  'inventario_solemne',
  'adopcion',
  'jurisdiccion_voluntaria',
  'homologacion_finiquito',
  'emancipacion',
  'autorizacion_salida',
])

export const ROL_CLIENTE_OPCIONES: Record<Materia, Opcion[]> = {
  civil: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  mercantil: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  laboral: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  familia: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  transito: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  inquilinato: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  contencioso_administrativo: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  contencioso_tributario: [
    { value: 'actor', label: 'Actor / Demandante' },
    { value: 'demandado', label: 'Demandado' },
    { value: 'tercero', label: 'Tercero interviniente' },
  ],
  penal: [
    { value: 'victima', label: 'Víctima / Ofendido' },
    { value: 'acusador_particular', label: 'Acusador particular' },
    { value: 'procesado', label: 'Procesado / Imputado' },
    { value: 'defensa', label: 'Defensa' },
  ],
  constitucional: [
    { value: 'accionante', label: 'Accionante' },
    { value: 'accionado', label: 'Accionado' },
    { value: 'tercero_interes', label: 'Tercero con interés' },
  ],
  asesoria: [{ value: 'cliente', label: 'Cliente' }],
  otro: [{ value: 'cliente', label: 'Cliente' }],
}

export const ROL_SOLICITANTE: Opcion = { value: 'solicitante', label: 'Solicitante' }

// Flujo de instancias por materia. Vacío = no aplica (se oculta el stepper).
export const INSTANCIAS_POR_MATERIA: Record<Materia, Opcion[]> = {
  civil: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
    { value: 'casacion_cnj', label: 'Casación CNJ' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  mercantil: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
    { value: 'casacion_cnj', label: 'Casación CNJ' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  laboral: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
  ],
  familia: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
    { value: 'casacion_cnj', label: 'Casación CNJ' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  inquilinato: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
    { value: 'casacion_cnj', label: 'Casación CNJ' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  transito: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
    { value: 'casacion_cnj', label: 'Casación CNJ' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  penal: [
    { value: 'instruccion_fiscal', label: 'Instrucción fiscal' },
    { value: 'audiencia_preparatoria', label: 'Audiencia preparatoria' },
    { value: 'juicio_oral', label: 'Juicio oral' },
    { value: 'apelacion', label: 'Apelación' },
    { value: 'casacion_cnj', label: 'Casación CNJ' },
  ],
  contencioso_administrativo: [
    { value: 'tribunal_distrital', label: 'Tribunal Distrital' },
    { value: 'corte_nacional', label: 'Corte Nacional' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  contencioso_tributario: [
    { value: 'tribunal_distrital', label: 'Tribunal Distrital' },
    { value: 'corte_nacional', label: 'Corte Nacional' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  constitucional: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'corte_provincial', label: 'Corte Provincial' },
    { value: 'corte_constitucional', label: 'Corte Constitucional' },
  ],
  asesoria: [],
  otro: [
    { value: 'primera_instancia', label: 'Primera instancia' },
    { value: 'segunda_instancia', label: 'Segunda instancia' },
  ],
}
